display_name: ARS Workspace
icon: linux/packaging/assets/logo.png
group: Applications/Office
vendor: African Research Society
packager: African Research Society
packagerEmail: npo@africanresearchsociety.org
license: APGL-3.0
url: https://africanresearchsociety.org

build_arch: x86_64

keywords:
  - ARS Workspace
  - Office
  - Document
  - Database
  - Note
  - Kanban
  - Note

generic_name: ARS Workspace

categories:
  - Office
  - Productivity

startup_notify: true

supportedMimeType: x-scheme-handler/ars-workspace

requires:
  - libnotify
  - keybinder
