display_name: ARS Workspace
package_name: appflowy

maintainer:
  name: African Research Society
  email: npo@africanresearchsociety.org

keywords:
  - ARS Workspace
  - Office
  - Document
  - Database
  - Note
  - Kanban
  - Note

installed_size: 100000
icon: linux/packaging/assets/logo.png

generic_name: ARS Workspace

categories:
  - Office
  - Productivity

startup_notify: true
essential: false

section: x11
priority: optional

supportedMimeType: x-scheme-handler/ars-workspace

dependencies:
  - libnotify-bin
  - libkeybinder-3.0-0
